include("convergence_plot_from_noise_order1.jl")
include("convergence_plot_from_noise_order2.jl")
include("plot_noise_order1.jl")
include("plot_noise_order2.jl")
include("plot_solutions_with_noise_order1.jl")
